//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soltius.RetailExcel.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soltius.RetailExcel.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationDetail]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationDetail](
        ///	[DummyKey] [int] IDENTITY(1,1) NOT NULL,
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[ItemCode] [nvarchar](40) NOT NULL,
        ///	[AcceptedQuantity] [decimal](19, 4) NOT NULL,
        ///	[Rejec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDeliveryValidationDetailTableCommandText {
            get {
                return ResourceManager.GetString("CreateDeliveryValidationDetailTableCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationHeader]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationHeader](
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[DocumentDateTime] [datetime] NOT NULL,
        ///	[DeliveryNoteNumber] [nvarchar](13) NOT NULL,
        ///	[CustomerGRNNumber] [nvarchar](50) NULL,
        ///	[D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDeliveryValidationHeaderTableCommandText {
            get {
                return ResourceManager.GetString("CreateDeliveryValidationHeaderTableCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[GeneralDescription]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[GeneralDescription](
        ///	[TableType] [int] NOT NULL,
        ///	[TableKey] [int] NOT NULL,
        ///	[ShortDescription] [nvarchar](50) NOT NULL,
        ///	[LongDescription] [nvarchar](200) NOT NULL,
        ///	[CreatedDateTime] [datetime] NOT NULL,
        ///	[CreatedUserID] [nvarchar](13) NOT NULL,
        ///	[ModifiedDateTime] [datetime] NOT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateGeneralDescriptionTableCommandText {
            get {
                return ResourceManager.GetString("CreateGeneralDescriptionTableCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @CUSTOMER TABLE (
        ///		CustomerCode				nvarchar(16)
        ///	,	CustomerName				nvarchar(150)
        ///	,	CategoryCode				nvarchar(4)
        ///	,	CategoryName				nvarchar(50)
        ///	,	SubCategoryCode				nvarchar(3)
        ///	,	SubCategoryName				nvarchar(50)
        ///)
        ///INSERT INTO @CUSTOMER
        ///SELECT	TOP 100 PERCENT
        ///			CustomerCode				=	CUS.CustomerCode
        ///		,	CustomerName				=	CUS.CustomerName
        ///		,	CategoryCode				=	CAT.CategoryCode
        ///		,	CategoryName				=	CAT.CategoryName
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetCustomerCommandText {
            get {
                return ResourceManager.GetString("GetCustomerCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber			=	CAST(T.DCD_LEVEL_NUMBER AS int)
        ///		,	OrganizationCode	=	T.DCD_ORG_CD
        ///		,	DocumentNumber		=	T.DCD_DOC_NO
        ///		,	ItemCode			=	T.DCD_ITM_CD
        ///		,	SalesUnit			=	T.DCD_UOM_CD
        ///		,	Quantity			=	T.DCD_QTY
        ///		,	UnitPrice			=	T.DCD_PRICE
        ///FROM	DELIVERY_CHELLAN_DTL T
        ///WHERE	(
        ///		T.DCD_ORG_CD = @OrganizationCode
        ///	AND	T.DCD_DOC_NO = @DocumentNumber
        ///).
        /// </summary>
        internal static string GetDeliveryNoteDetailByDocumentNumberCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryNoteDetailByDocumentNumberCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	DocumentNumber		=	A.DocumentNumber
        ///					,	DocumentDateTime	=	A.DocumentDateTime
        ///					,	CustomerCode		=	A.CustomerCode
        ///					,	CustomerName		=	C.CustomerName
        ///					,	SalesOrderNumber	=	A.SalesOrderNumber
        ///			FROM	(
        ///				SELECT	TOP 100 PE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryNoteHeaderByOrganizationCodeCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryNoteHeaderByOrganizationCodeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	DocumentNumber		=	A.DocumentNumber
        ///					,	DocumentDateTime	=	A.DocumentDateTime
        ///					,	CustomerCode		=	A.CustomerCode
        ///					,	CustomerName		=	C.CustomerName
        ///					,	SalesOrderNumber	=	A.SalesOrderNumber
        ///			FROM	(
        ///				SELECT	TOP 100 PE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryNoteHeaderCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryNoteHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	DocumentNumber		=	A.DocumentNumber
        ///					,	DocumentDateTime	=	A.DocumentDateTime
        ///					,	CustomerCode		=	A.CustomerCode
        ///					,	CustomerName		=	C.CustomerName
        ///					,	SalesOrderNumber	=	A.SalesOrderNumber
        ///			FROM	(
        ///				SELECT	TOP 100 PE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryNoteHeaderUnvalidatedCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryNoteHeaderUnvalidatedCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationDetail]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationDetail](
        ///	[DummyKey] [int] IDENTITY(1,1) NOT NULL,
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[ItemCode] [nvarchar](40) NOT NULL,
        ///	[AcceptedQuantity] [decimal](19, 4) NOT NULL,
        ///	[RejectedQuantity] [decimal](19, 4) NOT NULL,
        ///	[Discrepanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryValidationDetailByDocumentNumberCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryValidationDetailByDocumentNumberCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationDetail]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationDetail](
        ///	[DummyKey] [int] IDENTITY(1,1) NOT NULL,
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[ItemCode] [nvarchar](40) NOT NULL,
        ///	[AcceptedQuantity] [decimal](19, 4) NOT NULL,
        ///	[RejectedQuantity] [decimal](19, 4) NOT NULL,
        ///	[Discrepanc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryValidationDetailCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryValidationDetailCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationHeader]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationHeader](
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[DocumentDateTime] [datetime] NOT NULL,
        ///	[DeliveryNoteNumber] [nvarchar](13) NOT NULL,
        ///	[CustomerGRNNumber] [nvarchar](50) NULL,
        ///	[DocumentStatus] [nvarchar](1) NOT NULL,
        ///	[CreatedDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryValidationHeaderByDocumentNumberCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryValidationHeaderByDocumentNumberCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationHeader]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationHeader](
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[DocumentDateTime] [datetime] NOT NULL,
        ///	[DeliveryNoteNumber] [nvarchar](13) NOT NULL,
        ///	[CustomerGRNNumber] [nvarchar](50) NULL,
        ///	[DocumentStatus] [nvarchar](1) NOT NULL,
        ///	[CreatedDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryValidationHeaderByOrganizationCodeCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryValidationHeaderByOrganizationCodeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[DeliveryValidationHeader]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[DeliveryValidationHeader](
        ///	[LevelNumber] [int] NOT NULL,
        ///	[OrganizationCode] [nvarchar](3) NOT NULL,
        ///	[DocumentNumber] [nvarchar](13) NOT NULL,
        ///	[DocumentDateTime] [datetime] NOT NULL,
        ///	[DeliveryNoteNumber] [nvarchar](13) NOT NULL,
        ///	[CustomerGRNNumber] [nvarchar](50) NULL,
        ///	[DocumentStatus] [nvarchar](1) NOT NULL,
        ///	[CreatedDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeliveryValidationHeaderCommandText {
            get {
                return ResourceManager.GetString("GetDeliveryValidationHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N&apos;[dbo].[GeneralDescription]&apos;) AND OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///BEGIN
        ///CREATE TABLE [dbo].[GeneralDescription](
        ///	[TableType] [int] NOT NULL,
        ///	[TableKey] [int] NOT NULL,
        ///	[ShortDescription] [nvarchar](50) NOT NULL,
        ///	[LongDescription] [nvarchar](200) NOT NULL,
        ///	[CreatedDateTime] [datetime] NOT NULL,
        ///	[CreatedUserID] [nvarchar](13) NOT NULL,
        ///	[ModifiedDateTime] [datetime] NOT NULL,
        ///	[ModifiedUserID] [nvarchar](13) NOT NULL,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDescriptionCommandText {
            get {
                return ResourceManager.GetString("GetDescriptionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			DivisionCode	=	T.DIV_ID
        ///		,	DivisionName	=	T.DIV_DESC
        ///FROM	DIVISION_MST T.
        /// </summary>
        internal static string GetDivisionCommandText {
            get {
                return ResourceManager.GetString("GetDivisionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	DocumentNumber		=	A.DocumentNumber
        ///					,	DocumentDate		=	A.DocumentDateTime
        ///			FROM	(
        ///				SELECT	TOP 100 PERCENT
        ///							LevelNumber			=	CAST(T.GIH_LEVEL_NO AS int)
        ///						,	OrganizationCode	=	T.GIH_ORG_CD
        ///						,	DocumentNumber		=	T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetGRNHeaderCommandText {
            get {
                return ResourceManager.GetString("GetGRNHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @DeliveryNote TABLE (
        ///		LevelNumber				int
        ///	,	OrganizationCode		nvarchar(3)
        ///	,	DeliveryNoteNumber		nvarchar(13)
        ///	,	ItemCode				nvarchar(40)
        ///	,	Quantity				decimal(19,4)
        ///)
        ///INSERT INTO @DeliveryNote
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber				=	T.DCD_LEVEL_NUMBER
        ///		,	OrganizationCode		=	T.DCD_ORG_CD
        ///		,	DeliveryNoteNumber		=	T.DCD_DOC_NO
        ///		,	ItemCode				=	T.DCD_ITM_CD
        ///		,	Quantity				=	ISNULL(T.DCD_QTY, 0)
        ///FROM	DELIVERY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeByDeliveryNoteCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeByDeliveryNoteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @BarcodeList TABLE (
        ///		DivisionCode                nvarchar(3)
        ///	,   ItemCode					nvarchar(40)
        ///	,   Barcode						nvarchar(40)
        ///	,   ItemName					nvarchar(200)
        ///	,   SalesUnit					nvarchar(3)
        ///	,	BarcodeType					int
        ///	,   SellPrice					decimal(19,4)
        ///)
        ///INSERT INTO @BarcodeList
        ///SELECT	DISTINCT
        ///		TOP 100 PERCENT
        ///			DivisionCode	=	T.BICF_DIV_CD
        ///		,   ItemCode		=	T.BICF_ITEM_CODE
        ///		,   Barcode			=	T.BICF_BAR_CODE
        ///		,   ItemN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeByDivisionCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeByDivisionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @GRN TABLE (
        ///		LevelNumber				int
        ///	,	OrganizationCode		nvarchar(3)
        ///	,	SalesOrderNumber		nvarchar(13)
        ///	,	ItemCode				nvarchar(40)
        ///	,	Quantity				decimal(19,4)
        ///)
        ///INSERT INTO @GRN
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber				=	T.GID_LEVEL_NUMBER
        ///		,	OrganizationCode		=	T.GID_ORG_CD
        ///		,	PurchaseOrderNumber		=	T.GID_DOC_NO
        ///		,	ItemCode				=	T.GID_ITM_CD
        ///		,	Quantity				=	ISNULL(T.GID_PO_QTY, 0)
        ///FROM	GOODS_RECEIPT_DTL T
        ///WHE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeByGRNCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeByGRNCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @PurchaseOrder TABLE (
        ///		LevelNumber				int
        ///	,	OrganizationCode		nvarchar(3)
        ///	,	PurchaseOrderNumber		nvarchar(13)
        ///	,	ItemCode				nvarchar(40)
        ///	,	Quantity				decimal(19,4)
        ///)
        ///INSERT INTO @PurchaseOrder
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber				=	T.POD_LEVEL_NUMBER
        ///		,	OrganizationCode		=	T.POD_ORG_CD
        ///		,	PurchaseOrderNumber		=	T.POD_PO_NO
        ///		,	ItemCode				=	T.POD_ITM_CD
        ///		,	Quantity				=	ISNULL(T.POD_QTY, 0)
        ///FROM	PURCH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeByPurchaseOrderCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeByPurchaseOrderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @SalesOrder TABLE (
        ///		LevelNumber				int
        ///	,	OrganizationCode		nvarchar(3)
        ///	,	SalesOrderNumber		nvarchar(13)
        ///	,	ItemCode				nvarchar(40)
        ///	,	Quantity				decimal(19,4)
        ///)
        ///INSERT INTO @SalesOrder
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber				=	T.SOD_LEVEL_NUMBER
        ///		,	OrganizationCode		=	T.SOD_ORG_CD
        ///		,	PurchaseOrderNumber		=	T.SOD_DOC_NO
        ///		,	ItemCode				=	T.SOD_ITM_CD
        ///		,	Quantity				=	ISNULL(T.SOD_QTY, 0)
        ///FROM	SALES_ORDER_D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeBySalesOrderCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeBySalesOrderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @TransferOut TABLE (
        ///		SenderLevelNumber			int
        ///	,	SenderOrganizationCode		nvarchar(3)
        ///	,	SenderDocumentNumber		nvarchar(13)
        ///	,	ItemCode					nvarchar(40)
        ///	,	Quantity					decimal(19,4)
        ///)
        ///INSERT INTO @TransferOut
        ///SELECT	TOP 100 PERCENT
        ///			SenderLevelNumber		=	T.TOD_LEVEL_NUMBER
        ///		,	SenderOrganizationCode	=	T.TOD_ORG_CD
        ///		,	SenderDocumentNumber	=	T.TOD_DOC_NO
        ///		,	ItemCode				=	T.TOD_ITM_CD
        ///		,	Quantity				=	ISNULL(T.TOD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemBarcodeByTransferOutCommandText {
            get {
                return ResourceManager.GetString("GetItemBarcodeByTransferOutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			DivisionCode		=	A.ITM_DIV_CD
        ///		,	OldItemCode			=	ISNULL(A.ITM_OLD_ITM_CD, &apos;&apos;)
        ///		,	ItemCode			=	A.ITM_CD
        ///		,	ItemName			=	A.ITM_NAME
        ///		,	StockUnit			=	ISNULL(A.ITM_STOCK_UOM, &apos;&apos;)
        ///		,	PurchaseUnit		=	ISNULL(A.ITM_PURCHASE_UOM, &apos;&apos;)
        ///		,	SalesUnit			=	ISNULL(A.ITM_SALES_UOM, &apos;&apos;)
        ///FROM	ITEM_MST A
        ///		INNER JOIN DELIVERY_CHELLAN_DTL B
        ///		ON
        ///			A.ITM_CD = B.DCD_ITM_CD
        ///WHERE	(
        ///		B.DCD_ORG_CD = @OrganizationCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemByDeliveryNoteCommandText {
            get {
                return ResourceManager.GetString("GetItemByDeliveryNoteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			DivisionCode		=	A.DivisionCode
        ///		,	OldItemCode			=	A.OldItemCode
        ///		,	ItemCode			=	A.ItemCode
        ///		,	ItemName			=	A.ItemName
        ///		,	StockUnit			=	A.StockUnit
        ///		,	PurchaseUnit		=	A.PurchaseUnit
        ///		,	SalesUnit			=	A.SalesUnit
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						DivisionCode		=	T.ITM_DIV_CD
        ///					,	OldItemCode			=	ISNULL(T.ITM_OLD_ITM_CD, &apos;&apos;)
        ///					,	ItemCode			=	T.ITM_CD
        ///					,	ItemName			=	T.ITM_NAME
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemByDivisionCodeCommandText {
            get {
                return ResourceManager.GetString("GetItemByDivisionCodeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			DivisionCode		=	T.ITM_DIV_CD
        ///		,	OldItemCode			=	ISNULL(T.ITM_OLD_ITM_CD, &apos;&apos;)
        ///		,	ItemCode			=	T.ITM_CD
        ///		,	ItemName			=	T.ITM_NAME
        ///		,	StockUnit			=	ISNULL(T.ITM_STOCK_UOM, &apos;&apos;)
        ///		,	PurchaseUnit		=	ISNULL(T.ITM_PURCHASE_UOM, &apos;&apos;)
        ///		,	SalesUnit			=	ISNULL(T.ITM_SALES_UOM, &apos;&apos;)
        ///FROM	ITEM_MST T.
        /// </summary>
        internal static string GetItemCommandText {
            get {
                return ResourceManager.GetString("GetItemCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @Organization TABLE (
        ///		LevelNumber         int
        ///	,	LevelName			nvarchar(50)
        ///	,   OrganizationCode	nvarchar(3)
        ///	,   OrganizationName    nvarchar(50)
        ///)
        ///INSERT INTO @Organization
        ///SELECT  TOP 100 PERCENT
        ///			LevelNumber         =   CAST(T.ORG_LEVEL_NUMBER AS int)
        ///		,	LevelName			=	CASE T.ORG_LEVEL_NUMBER
        ///										WHEN 1 THEN &apos;HEAD OFFICE&apos;
        ///										WHEN 2 THEN &apos;WAREHOUSE&apos;
        ///										ELSE &apos;STORE&apos;
        ///									END
        ///		,   Organ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrganizationByOrganizationCodeCommandText {
            get {
                return ResourceManager.GetString("GetOrganizationByOrganizationCodeCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @Organization TABLE (
        ///		LevelNumber         int
        ///	,	LevelName			nvarchar(50)
        ///	,   OrganizationCode	nvarchar(3)
        ///	,   OrganizationName    nvarchar(50)
        ///)
        ///INSERT INTO @Organization
        ///SELECT  TOP 100 PERCENT
        ///			LevelNumber         =   CAST(T.ORG_LEVEL_NUMBER AS int)
        ///		,	LevelName			=	CASE T.ORG_LEVEL_NUMBER
        ///										WHEN 1 THEN &apos;HEAD OFFICE&apos;
        ///										WHEN 2 THEN &apos;WAREHOUSE&apos;
        ///										ELSE &apos;STORE&apos;
        ///									END
        ///		,   Organ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrganizationCommandText {
            get {
                return ResourceManager.GetString("GetOrganizationCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	PONumber			=	A.DocumentNumber
        ///					,	PODate				=	A.DocumentDateTime
        ///			FROM	(
        ///				SELECT	TOP 100 PERCENT
        ///							LevelNumber			=	CAST(T.POH_LEVEL_NUMBER AS int)
        ///						,	OrganizationCode	=	T.POH_ORG_CD
        ///						,	DocumentNumber		=	T.POH_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPurchaseOrderHeaderCommandText {
            get {
                return ResourceManager.GetString("GetPurchaseOrderHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		A.*
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	A.LevelNumber
        ///					,	OrganizationCode	=	A.OrganizationCode
        ///					,	OrganizationName	=	B.OrganizationName
        ///					,	DocumentNumber		=	A.DocumentNumber
        ///					,	DocumentDate		=	A.DocumentDateTime
        ///			FROM	(
        ///				SELECT	TOP 100 PERCENT
        ///							LevelNumber			=	CAST(T.SOH_LEVEL_NUMBER AS int)
        ///						,	OrganizationCode	=	T.SOH_ORG_CD
        ///						,	DocumentNumber	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSalesOrderHeaderCommandText {
            get {
                return ResourceManager.GetString("GetSalesOrderHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			SenderLevelNumber		=	A.SenderLevelNumber
        ///		,	SenderOrganizationCode	=	A.SenderOrganizationCode
        ///		,	SenderDocumentNumber	=	A.SenderDocumentNumber
        ///		,	ItemCode				=	A.ItemCode
        ///		,	ItemName				=	B.ItemName
        ///		,	TransferQuantity		=	A.TransferQuantity
        ///		,	TransferUnit			=	A.TransferUnit
        ///		,	CostPrice				=	A.CostPrice
        ///		,	TransferValue			=	CAST(A.TransferQuantity * A.CostPrice AS decimal(19,4))
        ///FROM	(
        ///			SE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTransferOutDetailByDocumentNumberCommandText {
            get {
                return ResourceManager.GetString("GetTransferOutDetailByDocumentNumberCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @Organization TABLE (
        ///		LevelNumber			int
        ///	,	OrganizationCode	nvarchar(3)
        ///	,	OrganizationName	nvarchar(50)
        ///)
        ///INSERT INTO @Organization
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber			=	CAST(T.ORG_LEVEL_NUMBER AS int)
        ///		,	OrganizationCode	=	T.ORG_CD
        ///		,	OrganizationName	=	T.ORG_NAME
        ///FROM	ORGANIZATION_MST T
        ///
        ///SELECT	TOP 100 PERCENT
        ///			SenderLevelNumber			=	A.SenderLevelNumber
        ///		,	SenderOrganizationCode		=	A.SenderOrganization [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetTransferOutHeaderCommandText {
            get {
                return ResourceManager.GetString("GetTransferOutHeaderCommandText", resourceCulture);
            }
        }
    }
}
