//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soltius.RetailExcel.Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soltius.RetailExcel.Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		IsAuthorized	=	COUNT(*)
        ///FROM	EMPLOYEE_MST T
        ///WHERE	(
        ///		(T.EMP_LEVEL_NUMBER = 1)
        ///	AND	(T.EMP_ORG_CD = &apos;001&apos;)
        ///	AND (T.EMP_LOGIN_NAME = &apos;ADMINISTRATOR&apos; AND T.EMP_LOGIN_NAME = @UserName)
        ///	AND (T.EMP_PWORD = @Password)
        ///).
        /// </summary>
        internal static string AdminLoginCommandText {
            get {
                return ResourceManager.GetString("AdminLoginCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///		IsAuthorized	=	COUNT(*)
        ///FROM	EMPLOYEE_MST T
        ///WHERE	(
        ///	(
        ///			(T.EMP_LEVEL_NUMBER = 1)
        ///		AND	(T.EMP_ORG_CD = &apos;001&apos;)
        ///		AND (T.EMP_LOGIN_NAME = &apos;ADMINISTRATOR&apos; AND T.EMP_LOGIN_NAME = @UserName)
        ///		AND (T.EMP_PWORD = @Password)
        ///	)
        ///	OR (
        ///			(T.EMP_ORG_CD = @OrganizationCode)
        ///		AND (T.EMP_LOGIN_NAME = @UserName)
        ///		AND (T.EMP_PWORD = @Password)
        ///		AND (T.EMP_STATUS = &apos;O&apos;)
        ///	)
        ///).
        /// </summary>
        internal static string EmployeeLoginCommandText {
            get {
                return ResourceManager.GetString("EmployeeLoginCommandText", resourceCulture);
            }
        }
        
        internal static byte[] ExcelStyleSheet {
            get {
                object obj = ResourceManager.GetObject("ExcelStyleSheet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///SET NOCOUNT ON;
        ///
        ///SELECT	TOP 100 PERCENT
        ///			LevelNumber			=	A.LevelNumber
        ///		,	OrganizationCode	=	A.OrganizationCode
        ///		,	OrganizationName	=	B.OrganizationName
        ///		,	EmployeeCode		=	A.EmployeeCode
        ///		,	EmployeeName		=	A.EmployeeName
        ///		,	LoginName			=	A.LoginName
        ///FROM	(
        ///			SELECT	TOP 100 PERCENT
        ///						LevelNumber			=	CAST(A.EMP_LEVEL_NUMBER AS int)
        ///					,	OrganizationCode	=	A.EMP_ORG_CD
        ///					,	EmployeeCode		=	A.EMP_CD
        ///					,	EmployeeName		=	A.EMP_NAM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEmployeeByLoginCommandText {
            get {
                return ResourceManager.GetString("GetEmployeeByLoginCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
        ///SET NOCOUNT ON;
        ///
        ///DECLARE @Organization TABLE (
        ///		LevelNumber         int
        ///	,	LevelName			nvarchar(50)
        ///	,   OrganizationCode	nvarchar(3)
        ///	,   OrganizationName    nvarchar(50)
        ///)
        ///INSERT INTO @Organization
        ///SELECT  TOP 100 PERCENT
        ///			LevelNumber         =   CAST(T.ORG_LEVEL_NUMBER AS int)
        ///		,	LevelName			=	CASE T.ORG_LEVEL_NUMBER
        ///										WHEN 1 THEN &apos;HEAD OFFICE&apos;
        ///										WHEN 2 THEN &apos;WAREHOUSE&apos;
        ///										ELSE &apos;STORE&apos;
        ///									END
        ///		,   Organiz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetOrganizationCommandText {
            get {
                return ResourceManager.GetString("GetOrganizationCommandText", resourceCulture);
            }
        }
    }
}
